from typing import Any, Literal

from pydantic import BaseModel, Field


# ==========================================
# 1. Tool Input Schemas
# ==========================================
class CalculatorInput(BaseModel):
    """Input schema for the calculator tool."""

    expression: str = Field(
        description="The mathematical expression string to be evaluated, e.g., '2 * (3 + 4)' or '1024 / 8'."
    )


class ReadFileInput(BaseModel):
    """Input schema for the file reading tool."""

    path: str = Field(
        description="The absolute or relative path to the local target file, e.g., './data/config.json' or '/var/log/app.log'."
    )


class SearchWebInput(BaseModel):
    """Input schema for the web search tool."""

    query: str = Field(
        description="The search keywords or natural language query used to retrieve information from the web, e.g., 'Python dataclass decorator usage'."
    )
    max_results: int = Field(
        default=5,
        ge=1,
        le=20,
        description="The maximum number of search results to return. Defaults to 5.",
    )


class FetchUrlInput(BaseModel):
    """Input schema for the URL fetching tool."""

    url: str = Field(
        description="The complete URL of the webpage or API endpoint to fetch, including the protocol prefix, e.g., 'https://example.com/api/data'."
    )


# ==========================================
# 2. Agent Internal Data Structures
# ==========================================


class ToolCall(BaseModel):
    """Represents a tool call request initiated by the Agent."""

    name: str = Field(
        description="The name of the tool being called. Must strictly match the registered tool name, e.g., 'calculator'."
    )
    input: dict[str, Any] = Field(
        description="A dictionary of input arguments passed to the tool, matching the corresponding tool's input schema, e.g., {'expression': '1+1'}."
    )
    tool_use_id: str = Field(
        description="The globally unique identifier for this specific tool call generated by the model (e.g., Anthropic Claude), used to map results back to this call."
    )


class ToolResult(BaseModel):
    """Represents the execution result returned by a tool to the Agent."""

    type: Literal["tool_result"] = "tool_result"
    tool_use_id: str = Field(
        description="The unique identifier corresponding to the original tool call. Must strictly match the tool_use_id in the ToolCall."
    )
    content: str = Field(
        description="The raw string output generated by the tool. Complex structures or JSON data should be serialized into a string first."
    )
    is_error: bool = Field(
        default=False,
        description="A flag indicating whether an exception or error occurred during tool execution. Defaults to False.",
    )


class AgentStep(BaseModel):
    step_number: int = Field(ge=1)
    stop_reason: str | None
    text: list[str] = Field(default_factory=list)
    tool_calls: list[ToolCall] = Field(default_factory=list)
    tool_results: list[ToolResult] = Field(default_factory=list)
